### ISSUE TITLE
Looks like a great tool, however I can't get it to work on Ubuntu 15.04 with Docker 1.8.1

### ISSUE THREAD

**Issue by hookenz** [dreamcat4/docker-images#12]
My docker-compose.yml currently contains:
I'm just following your example and adding an IP to the first node in my cluster.

```
couchbase1:
  container_name: couchbase1
  image: couchbase/server:community-3.0.1 
  ports:
    - "8091:8091"
  volumes:
    - /opt/couchbase/node1:/opt/couchbase/var
  environment:
    - pipework_cmd=eth0 @CONTAINER_NAME@ 192.168.1.101/24@192.168.1.1 0a:00:01:01:01:01

couchbase2:
  container_name: couchbase2
  image: couchbase/server:community-3.0.1
  volumes:
    - /opt/couchbase/node2:/opt/couchbase/var

couchbase3:
  container_name: couchbase3
  image: couchbase/server:community-3.0.1 
  volumes:
    - /opt/couchbase/node3:/opt/couchbase/var

pipework:
  image: dreamcat4/pipework
  restart: always
  volumes:
    - /var/run/docker.sock:/docker.sock
  privileged: true
  pid: host 
  net: host
  environment:
    - run_mode=batch,daemon
    - host_routes=true
```

However, as you can see it doesn't work.

```
Attaching to couchbase1, couchbase3, couchbase2, couchbase_pipework_1
pipework_1   | WARNING: No swap limit support
pipework_1   | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
pipework_1   | event_line=2015-09-08T23:49:06.000000000Z d09a9ca3f2bb785763504df36fca52ba45cb2e1a9e9f12317e5e74b43d4ac072: (from dreamcat4/pipework) start
pipework_1   | WARNING: No swap limit support
pipework_1   | ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted

pipework_1   | /entrypoint.sh: line 147: printf: 099: invalid octal number
```
