### ISSUE TITLE
How do you use --direct-phys?

### ISSUE THREAD

**Issue by FallingSnow** [dreamcat4/docker-images#55]
I'm trying to pass an SR-IOV interface to a test container but adding `--direct-phys` seems to be parsed incorrectly.

```yaml
myapp:
  image: alpine
  command: sleep inf
  environment:
    - pipework_cmd=--direct-phys eth5 @CONTAINER_NAME@ udhcpc
  net: none

pipework:
  image: dreamcat4/pipework:latest
  restart: always
  volumes:
    - /var/run/docker.sock:/docker.sock
  privileged: true
  pid: host # THIS REQUIRES COMPOSE v1.3.0 & DOCKER v1.6.0
  net: host
  environment:
    #- debug=true
    - run_mode=batch,daemon
    - host_routes=true
    - route_add_delay=1
```

Output from `docker-compose up`:
(Note the `pipework_1  | /entrypoint.sh: line 190: set: --: invalid option` line)
```
Recreating test_pipework_1 ... done
Starting test_myapp_1      ... done
Attaching to test_pipework_1, test_myapp_1
pipework_1  | ln: failed to create symbolic link '/sys/fs/cgroup/openrc/name=openrc': Operation not permitted
pipework_1  | /entrypoint.sh: line 190: set: --: invalid option
pipework_1  | set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
pipework_1  | Device "eth1" does not exist.
pipework_1  | event_line=2022-05-08T20:33:35.700228242Z container start f86c1f1a102f483f802ffa0db3f9bee29be14fc91b5385380789ac955fad216d (com.docker.compose.config-hash=4c7d33be91c4b5e95432c49c4faa425f9378546b38a366f1704e594a9ccbd773, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=test, com.docker.compose.project.config_files=docker-compose.yml, com.docker.compose.project.working_dir=/opt/docker/test, com.docker.compose.service=pipework, com.docker.compose.version=1.29.2, image=dreamcat4/pipework:latest, name=test_pipework_1)
pipework_1  | event_line=2022-05-08T20:33:35.787127797Z container start f6dfcc6f7ed3eee8631dcb7cbd382962445120d901ac8ac16e485834122a472c (com.docker.compose.config-hash=81a7c0e72c42a72d5316b36c8961531b614684662726684d402794969a89de26, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=test, com.docker.compose.project.config_files=docker-compose.yml, com.docker.compose.project.working_dir=/opt/docker/test, com.docker.compose.service=myapp, com.docker.compose.version=1.29.2, image=alpine, name=test_myapp_1)
pipework_1  | /entrypoint.sh: line 190: set: --: invalid option
pipework_1  | set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
pipework_1  | Device "eth1" does not exist.
```
